def rand_range(min_val=0,
               max_val=1,
               seed=1618033988):
    """
    :param min_val: Low bound of random number
    :param max_val: High bound of random number
    :param seed: RNG seed
    :return: a generator yielding floats between min_val and max_val, generated by a standard
             Linear Congruential Generator (LCG)

             seed = (seed * multiplier + offset) % modulus
             u = seed / modulus

             out = min_val + (max_val - min_val) * u
    """
    # Necessary constants
    modulus = (2 ** 31) - 1  # Really big modulus helps with uniformity
    multiplier = 66743
    offset = 1
    seed = seed

    while True:
        seed = (seed * multiplier + offset) % modulus
        u = seed / modulus

        yield min_val + (max_val - min_val) * u
